### ISSUE TITLE
.env.example

### ISSUE THREAD

**Issue by cdiaz** [NicoPennec/nuxt-weather#1]
Hi Nicolas, you can put a .env file example to know the names of environments vars?.
Thanks

**Comment by NicoPennec** [comment]
Sorry, but I don't use any environment var for this project.
Can you tell me more about your issue?

**Comment by cdiaz** [comment]
I had not seen where put the vars for DEV_API and PROD_API,  But now understand.
Thanks

**Comment by NicoPennec** [comment]
a little warning: don't forget the CORS limitation on XHR request
